services:
  mongodb:
    build: ./docker/mongodb
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongodb_data:/data/db

  elasticsearch:
    build: ./docker/elasticsearch
    container_name: elasticsearch
    environment:
      - node.name=es01
      - ES_JAVA_OPTS=-Xmx2048m -Xms2048m
      - bootstrap.memory_lock=true
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD}
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./docker/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks: 
      - elk

  kibana:
    build: ./docker/kibana
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
      - setup-users
    environment:
      - ELASTICSEARCH_USERNAME=${KIBANA_USERNAME}
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      - XPACK_ENCRYPTED_SESSION_KEY=${XPACK_ENCRYPTED_SESSION_KEY}
    networks:
      - elk
    volumes: 
      - ./docker/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
  
  setup-users:
    build:
      context: ./docker/setup
      args:
        ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_PASSWORD}
        KIBANA_PASSWORD: ${KIBANA_PASSWORD}
        ES_URL: ${ELASTIC_URI}
    depends_on:
      - elasticsearch
    networks:
      - elk
  
  # monstache:
  #   build: ./docker/monstache
  #   container_name: monstache
  #   environment:
  #     - MONSTACHE_ES_USER=${ELASTICSEARCH_USERNAME}
  #     - MONSTACHE_ES_PASS=${ELASTICSEARCH_PASSWORD}
  #     - MONSTACHE_MONGO_URL=${MONGO_URI}
  #   volumes:
  #     - monstachedata:/monstache/
  #   depends_on:
  #     - mongodb
  #   networks:
  #     - db
  #     - elk
  #   env_file:
  #     - .env

  server:
    build: ./server
    container_name: ticket-app-backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - elasticsearch
      # - monstache
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - MONGO_URI=${MONGO_URI}
      - ELASTIC_URI=${ELASTIC_URI}
    volumes:
      - ./server:/usr/src/app

networks: 
  elk:
    driver: bridge
  
volumes:
  mongodb_data:
  esdata:
  # monstachedata: